export const SITE_NAME = "미플즈";
export const SITE_DESCRIPTION = "보드게임 동아리 미플즈 커뮤니티";
export const ADMIN_PASSWORD = "meeplez2024";
export const POSTS_PER_PAGE = 10;
export const CARDS_PER_PAGE = 9;
export const MAX_IMAGES = 5;
export const STORAGE_KEY = "meeplez-posts";
export const ADMIN_KEY = "meeplez-admin";
export const AUTHOR_KEY = "meeplez-author";
